#!/bin/bash
set -e

# When invoked as an Xcode scheme pre-action, SRCROOT is provided by Xcode.
# When run standalone, derive it from this script's location.
if [ -z "$SRCROOT" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SRCROOT="$(dirname "$SCRIPT_DIR")"
fi

cd "${SRCROOT}" || exit 1

GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

if [ -z "$GIT_TAG" ]; then
    VERSION="1.0.0"
else
    VERSION="${GIT_TAG#v}"
fi

# Build number: total commit count
COMMIT_COUNT=$(git rev-list HEAD --count 2>/dev/null || echo "1")
if [ -z "$COMMIT_COUNT" ] || [ "$COMMIT_COUNT" -eq 0 ]; then
    COMMIT_COUNT="1"
fi

echo "Setting version: ${VERSION}, build: ${COMMIT_COUNT}"

mkdir -p "${SRCROOT}/Config"

cat > "${SRCROOT}/Config/Version.generated.xcconfig" << XCEOF
// Auto-generated by set_version.sh - Do not edit manually
MARKETING_VERSION = ${VERSION}
CURRENT_PROJECT_VERSION = ${COMMIT_COUNT}
XCEOF

echo "Version xcconfig updated successfully"
